homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret home_time_zone
  # Customization file
  customize: !include_dir_merge_named components/customizations

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

lovelace:
  mode: yaml

panel_iframe: !include components/panel.yaml

# Enables configuration UI
config:

# SSL Enabled using (Hass.io plugin - Duck DNS)
http:
  base_url: !secret ha_base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Cloud
cloud:

sun:

#######################################################################################
#                                                                                     #
#                       COMPONENTS                                                    #
#                                                                                     #
#######################################################################################
# Using IFTTT for quite a few components that support this more than home assistant
#
# https://www.home-assistant.io/components/ifttt/
ifttt:
  key: !secret ifttt_api_key
#######################################################################################

#######################################################################################
# HVAC system
#
# https://www.home-assistant.io/components/ecobee/
ecobee:
  api_key: !secret ecobee_api_key
#######################################################################################


#######################################################################################
# Customized iOS push Notifications for Home Assistant / Node-Red
# TODO: File Structure
ios:
  push:
    categories:
      - name: Home
        identifier: 'home'
        actions:
          - identifier: 'NO_MUSIC'
            title: 'Turn off music'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
          - identifier: 'RAISE_BLINDS'
            title: 'Raise Shades'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
      - name: Upstairs
        identifier: 'upstairs'
        actions:
          - identifier: 'UNLOCK_DOOR'
            title: 'Unlock door'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
          - identifier: 'DOWNSTAIRS'
            title: 'Go Downstairs'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
#######################################################################################


#######################################################################################
# Nest Components
# - smoke detector / CO detector
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
#######################################################################################


#######################################################################################
# The input_boolean component allows the user to define boolean values that
# can be controlled via the frontend and can be used within conditions of
# automation. This can for example be used to disable or enable certain
# automations.
#
# https://www.home-assistant.io/components/input_boolean/
#
input_boolean: !include_dir_merge_named components/input_booleans
#######################################################################################


#######################################################################################
# This handles my automations within Home Assistant
#   almost all my automations are handled within Node-Red
# https://www.home-assistant.io/docs/automation/
#
automation: !include_dir_merge_list components/automations
#######################################################################################


#######################################################################################
# Binary sensors in Home Assistant
#
# https://www.home-assistant.io/components/binary_sensor/
binary_sensor: !include_dir_list components/binary_sensors
#######################################################################################


#######################################################################################
# Tracking all devices through Home Assistant
#  - Bluetooth
#  - Router
#  - GPS
# https://www.home-assistant.io/components/device_tracker/
device_tracker: !include components/device_tracker.yaml
#######################################################################################


#######################################################################################
# Asus Router utilized for device_tracker
#
# https://www.home-assistant.io/components/asuswrt/
asuswrt:
  host: !secret router_ip_address
  username: !secret router_username
  password: !secret router_password
#######################################################################################


#######################################################################################
# Media players in Home Assistant
#
# https://www.home-assistant.io/components/media_player/
media_player: !include_dir_merge_list components/media_players
#######################################################################################

#######################################################################################
# All custom scripts that do multiple actions with one call
#
# https://www.home-assistant.io/components/script
script: !include_dir_merge_named components/scripts
#######################################################################################


#######################################################################################
# All Sensors that are in Home Assistant
#
# https://www.home-assistant.io/components/sensor
sensor: !include_dir_merge_list components/sensors
#######################################################################################


#######################################################################################
# Custom Switches in Home Assistant
#
# https://www.home-assistant.io/components/switch/
switch: !include_dir_merge_list components/switches
#######################################################################################


#######################################################################################
# WeMo Plugs and Misc
#
# https://www.home-assistant.io/components/wemo/
wemo:
#######################################################################################


#######################################################################################
# Enables Wake on LAN domain
#
# https://www.home-assistant.io/components/wake_on_lan/
wake_on_lan:
#######################################################################################


#######################################################################################
# Zones allow you to specify certain regions on earth (for now).
#
# https://www.home-assistant.io/components/zone/
#
zone: !include_dir_merge_list components/zones
#######################################################################################


#######################################################################################
# Weather configuration in Home Assistant
#   Used for overall weather on lovelace page 
#
# https://www.home-assistant.io/components/weather/
weather: !include_dir_list components/weather
#######################################################################################


#######################################################################################
#
#                      NOT USED COMPONENTS
#
#######################################################################################
#Not Used
group:
scene: