####################################################
#                                                  #
#                     NAS                          #
#                                                  #
####################################################
- platform: synologydsm
  host: !secret nas_ip_address
  username: !secret nas_username
  password: !secret nas_password
  monitored_conditions:
    - disk_smart_status
    - disk_status
    - volume_percentage_used
    - volume_disk_temp_avg
    - volume_disk_temp_max
    - disk_below_remain_life_thr
    - cpu_total_load